#url: http://ervinb.github.io

harmony:
  name: ervin's blog
  description: Tips and tricks to try before you strangle yourself with a wireless mouse
  meta_description: > # 
    Blog about handy tips and tricks about programming, Linux/Windows system administration and life.
  basetheme: darken #theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Ervin Barta
    email: ervin@renderedtext.com
    url: http://ervinb.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-64733189-1

  # Profile links, leave blank to ignore
  social: 
    github: ervinb
    twitter: baer
    facebook: ervin.barta
    gplus: +ErvinBarta1
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - vendor

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
